#!/usr/bin/env node

try { require('newrelic') } catch (e) {}

var path = require('path');
var fs   = require('fs');
var src  = path.dirname(fs.realpathSync(__filename));

require(src + "/js/src/runner.js")
